
theme: jekyll-theme-minimal
title: Kajuun's homepage
description: Whatever happened to a simple index.html, this jekyll nonsense seems unnecessarily complex, I think I'll stick to standard html... but followed GitHub's guide, so maybe this is needed for something.
